[build]
  command = "npm run build"
  publish = "build"

[environment]
  REACT_APP_API_URL = "https://certificate-generator-3bma.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
